import type { Metadata } from "next";
import "./globals.css";
import LayoutSite from "./layout.c";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <LayoutSite>{children}</LayoutSite>
      </body>
    </html>
  );
}
